CREATE DATABASE keycloak;
CREATE DATABASE tokenissuer;

CREATE USER keycloak WITH PASSWORD 'keycloak';
CREATE USER tokenissuer WITH PASSWORD 'tokenissuer';

GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
GRANT ALL PRIVILEGES ON DATABASE tokenissuer TO tokenissuer;

\c keycloak
ALTER SCHEMA public OWNER TO keycloak;
GRANT USAGE, CREATE ON SCHEMA public TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO keycloak;

\c tokenissuer
ALTER SCHEMA public OWNER TO tokenissuer;
GRANT USAGE, CREATE ON SCHEMA public TO tokenissuer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO tokenissuer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO tokenissuer;
