// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/jwks/jwks.go

// Package jwksmocks is a generated GoMock package.
package jwksmocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJWKS is a mock of JWKS interface.
type MockJWKS struct {
	ctrl     *gomock.Controller
	recorder *MockJWKSMockRecorder
}

// MockJWKSMockRecorder is the mock recorder for MockJWKS.
type MockJWKSMockRecorder struct {
	mock *MockJWKS
}

// NewMockJWKS creates a new mock instance.
func NewMockJWKS(ctrl *gomock.Controller) *MockJWKS {
	mock := &MockJWKS{ctrl: ctrl}
	mock.recorder = &MockJWKSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWKS) EXPECT() *MockJWKSMockRecorder {
	return m.recorder
}

// GetPublicKey mocks base method.
func (m *MockJWKS) GetPublicKey() (*rsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey")
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockJWKSMockRecorder) GetPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockJWKS)(nil).GetPublicKey))
}
