// Code generated by MockGen. DO NOT EDIT.
// Source: token.go

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	reflect "reflect"
	identifier "tokenissuer/internal/adapter/identifier"

	gomock "github.com/golang/mock/gomock"
)

// MockToken is a mock of Token interface.
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMockRecorder
}

// MockTokenMockRecorder is the mock recorder for MockToken.
type MockTokenMockRecorder struct {
	mock *MockToken
}

// NewMockToken creates a new mock instance.
func NewMockToken(ctrl *gomock.Controller) *MockToken {
	mock := &MockToken{ctrl: ctrl}
	mock.recorder = &MockTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToken) EXPECT() *MockTokenMockRecorder {
	return m.recorder
}

// GetTokenPair mocks base method.
func (m *MockToken) GetTokenPair(ctx context.Context, code, redirectURL string) (identifier.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenPair", ctx, code, redirectURL)
	ret0, _ := ret[0].(identifier.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenPair indicates an expected call of GetTokenPair.
func (mr *MockTokenMockRecorder) GetTokenPair(ctx, code, redirectURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenPair", reflect.TypeOf((*MockToken)(nil).GetTokenPair), ctx, code, redirectURL)
}

// RefreshTokenPair mocks base method.
func (m *MockToken) RefreshTokenPair(ctx context.Context, refreshToken string) (identifier.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokenPair", ctx, refreshToken)
	ret0, _ := ret[0].(identifier.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokenPair indicates an expected call of RefreshTokenPair.
func (mr *MockTokenMockRecorder) RefreshTokenPair(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokenPair", reflect.TypeOf((*MockToken)(nil).RefreshTokenPair), ctx, refreshToken)
}
