// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/jwksloader/service.go

// Package jwksloadermocks is a generated GoMock package.
package jwksloadermocks

import (
	context "context"
	reflect "reflect"
	jwks "tokenissuer/pkg/jwks"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// LoadJWKS mocks base method.
func (m *MockService) LoadJWKS(ctx context.Context) (map[string]jwks.JWKS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadJWKS", ctx)
	ret0, _ := ret[0].(map[string]jwks.JWKS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadJWKS indicates an expected call of LoadJWKS.
func (mr *MockServiceMockRecorder) LoadJWKS(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadJWKS", reflect.TypeOf((*MockService)(nil).LoadJWKS), ctx)
}
