// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/tokenissuer.proto

package tokenissuerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_tokenissuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenissuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tokenissuer_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_tokenissuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenissuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_tokenissuer_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *VerifyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_tokenissuer_proto protoreflect.FileDescriptor

const file_proto_tokenissuer_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tokenissuer.proto\x12\vtokenissuer\"Q\n" +
	"\rVerifyRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\"Y\n" +
	"\x0eVerifyResponse\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email2R\n" +
	"\rTokenVerifier\x12A\n" +
	"\x06Verify\x12\x1a.tokenissuer.VerifyRequest\x1a\x1b.tokenissuer.VerifyResponseB\x14Z\x12./pb/tokenissuerpbb\x06proto3"

var (
	file_proto_tokenissuer_proto_rawDescOnce sync.Once
	file_proto_tokenissuer_proto_rawDescData []byte
)

func file_proto_tokenissuer_proto_rawDescGZIP() []byte {
	file_proto_tokenissuer_proto_rawDescOnce.Do(func() {
		file_proto_tokenissuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tokenissuer_proto_rawDesc), len(file_proto_tokenissuer_proto_rawDesc)))
	})
	return file_proto_tokenissuer_proto_rawDescData
}

var file_proto_tokenissuer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tokenissuer_proto_goTypes = []any{
	(*VerifyRequest)(nil),  // 0: tokenissuer.VerifyRequest
	(*VerifyResponse)(nil), // 1: tokenissuer.VerifyResponse
}
var file_proto_tokenissuer_proto_depIdxs = []int32{
	0, // 0: tokenissuer.TokenVerifier.Verify:input_type -> tokenissuer.VerifyRequest
	1, // 1: tokenissuer.TokenVerifier.Verify:output_type -> tokenissuer.VerifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tokenissuer_proto_init() }
func file_proto_tokenissuer_proto_init() {
	if File_proto_tokenissuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tokenissuer_proto_rawDesc), len(file_proto_tokenissuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tokenissuer_proto_goTypes,
		DependencyIndexes: file_proto_tokenissuer_proto_depIdxs,
		MessageInfos:      file_proto_tokenissuer_proto_msgTypes,
	}.Build()
	File_proto_tokenissuer_proto = out.File
	file_proto_tokenissuer_proto_goTypes = nil
	file_proto_tokenissuer_proto_depIdxs = nil
}
