// Code generated by MockGen. DO NOT EDIT.
// Source: model/subject.go

// Package modelmocks is a generated GoMock package.
package modelmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSubject is a mock of Subject interface.
type MockSubject struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectMockRecorder
}

// MockSubjectMockRecorder is the mock recorder for MockSubject.
type MockSubjectMockRecorder struct {
	mock *MockSubject
}

// NewMockSubject creates a new mock instance.
func NewMockSubject(ctrl *gomock.Controller) *MockSubject {
	mock := &MockSubject{ctrl: ctrl}
	mock.recorder = &MockSubjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubject) EXPECT() *MockSubjectMockRecorder {
	return m.recorder
}

// GetEmail mocks base method.
func (m *MockSubject) GetEmail() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmail")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEmail indicates an expected call of GetEmail.
func (mr *MockSubjectMockRecorder) GetEmail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmail", reflect.TypeOf((*MockSubject)(nil).GetEmail))
}

// GetName mocks base method.
func (m *MockSubject) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockSubjectMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockSubject)(nil).GetName))
}

// GetSubjectId mocks base method.
func (m *MockSubject) GetSubjectId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubjectId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSubjectId indicates an expected call of GetSubjectId.
func (mr *MockSubjectMockRecorder) GetSubjectId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubjectId", reflect.TypeOf((*MockSubject)(nil).GetSubjectId))
}
