// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/identifier/service.go

// Package identifiermocks is a generated GoMock package.
package identifiermocks

import (
	context "context"
	reflect "reflect"
	identifier "tokenissuer/internal/adapter/identifier"
	jwks "tokenissuer/pkg/jwks"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenPair is a mock of TokenPair interface.
type MockTokenPair struct {
	ctrl     *gomock.Controller
	recorder *MockTokenPairMockRecorder
}

// MockTokenPairMockRecorder is the mock recorder for MockTokenPair.
type MockTokenPairMockRecorder struct {
	mock *MockTokenPair
}

// NewMockTokenPair creates a new mock instance.
func NewMockTokenPair(ctrl *gomock.Controller) *MockTokenPair {
	mock := &MockTokenPair{ctrl: ctrl}
	mock.recorder = &MockTokenPairMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenPair) EXPECT() *MockTokenPairMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockTokenPair) GetAccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockTokenPairMockRecorder) GetAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockTokenPair)(nil).GetAccessToken))
}

// GetExpiresIn mocks base method.
func (m *MockTokenPair) GetExpiresIn() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiresIn")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetExpiresIn indicates an expected call of GetExpiresIn.
func (mr *MockTokenPairMockRecorder) GetExpiresIn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiresIn", reflect.TypeOf((*MockTokenPair)(nil).GetExpiresIn))
}

// GetRefreshExpiresIn mocks base method.
func (m *MockTokenPair) GetRefreshExpiresIn() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshExpiresIn")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRefreshExpiresIn indicates an expected call of GetRefreshExpiresIn.
func (mr *MockTokenPairMockRecorder) GetRefreshExpiresIn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshExpiresIn", reflect.TypeOf((*MockTokenPair)(nil).GetRefreshExpiresIn))
}

// GetRefreshToken mocks base method.
func (m *MockTokenPair) GetRefreshToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockTokenPairMockRecorder) GetRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockTokenPair)(nil).GetRefreshToken))
}

// GetTokenType mocks base method.
func (m *MockTokenPair) GetTokenType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTokenType indicates an expected call of GetTokenType.
func (mr *MockTokenPairMockRecorder) GetTokenType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenType", reflect.TypeOf((*MockTokenPair)(nil).GetTokenType))
}

// MockCodeExchanger is a mock of CodeExchanger interface.
type MockCodeExchanger struct {
	ctrl     *gomock.Controller
	recorder *MockCodeExchangerMockRecorder
}

// MockCodeExchangerMockRecorder is the mock recorder for MockCodeExchanger.
type MockCodeExchangerMockRecorder struct {
	mock *MockCodeExchanger
}

// NewMockCodeExchanger creates a new mock instance.
func NewMockCodeExchanger(ctrl *gomock.Controller) *MockCodeExchanger {
	mock := &MockCodeExchanger{ctrl: ctrl}
	mock.recorder = &MockCodeExchangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeExchanger) EXPECT() *MockCodeExchangerMockRecorder {
	return m.recorder
}

// ExchangeCode mocks base method.
func (m *MockCodeExchanger) ExchangeCode(ctx context.Context, code, redirectURL string) (identifier.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code, redirectURL)
	ret0, _ := ret[0].(identifier.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockCodeExchangerMockRecorder) ExchangeCode(ctx, code, redirectURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockCodeExchanger)(nil).ExchangeCode), ctx, code, redirectURL)
}

// MockTokenRefresher is a mock of TokenRefresher interface.
type MockTokenRefresher struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRefresherMockRecorder
}

// MockTokenRefresherMockRecorder is the mock recorder for MockTokenRefresher.
type MockTokenRefresherMockRecorder struct {
	mock *MockTokenRefresher
}

// NewMockTokenRefresher creates a new mock instance.
func NewMockTokenRefresher(ctrl *gomock.Controller) *MockTokenRefresher {
	mock := &MockTokenRefresher{ctrl: ctrl}
	mock.recorder = &MockTokenRefresherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRefresher) EXPECT() *MockTokenRefresherMockRecorder {
	return m.recorder
}

// Refresh mocks base method.
func (m *MockTokenRefresher) Refresh(ctx context.Context, refreshToken string) (identifier.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(identifier.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockTokenRefresherMockRecorder) Refresh(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockTokenRefresher)(nil).Refresh), ctx, refreshToken)
}

// MockJWKSLoader is a mock of JWKSLoader interface.
type MockJWKSLoader struct {
	ctrl     *gomock.Controller
	recorder *MockJWKSLoaderMockRecorder
}

// MockJWKSLoaderMockRecorder is the mock recorder for MockJWKSLoader.
type MockJWKSLoaderMockRecorder struct {
	mock *MockJWKSLoader
}

// NewMockJWKSLoader creates a new mock instance.
func NewMockJWKSLoader(ctrl *gomock.Controller) *MockJWKSLoader {
	mock := &MockJWKSLoader{ctrl: ctrl}
	mock.recorder = &MockJWKSLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWKSLoader) EXPECT() *MockJWKSLoaderMockRecorder {
	return m.recorder
}

// LoadJWKS mocks base method.
func (m *MockJWKSLoader) LoadJWKS(ctx context.Context) (map[string]jwks.JWKS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadJWKS", ctx)
	ret0, _ := ret[0].(map[string]jwks.JWKS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadJWKS indicates an expected call of LoadJWKS.
func (mr *MockJWKSLoaderMockRecorder) LoadJWKS(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadJWKS", reflect.TypeOf((*MockJWKSLoader)(nil).LoadJWKS), ctx)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ExchangeCode mocks base method.
func (m *MockService) ExchangeCode(ctx context.Context, code, redirectURL string) (identifier.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code, redirectURL)
	ret0, _ := ret[0].(identifier.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockServiceMockRecorder) ExchangeCode(ctx, code, redirectURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockService)(nil).ExchangeCode), ctx, code, redirectURL)
}

// LoadJWKS mocks base method.
func (m *MockService) LoadJWKS(ctx context.Context) (map[string]jwks.JWKS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadJWKS", ctx)
	ret0, _ := ret[0].(map[string]jwks.JWKS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadJWKS indicates an expected call of LoadJWKS.
func (mr *MockServiceMockRecorder) LoadJWKS(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadJWKS", reflect.TypeOf((*MockService)(nil).LoadJWKS), ctx)
}

// Refresh mocks base method.
func (m *MockService) Refresh(ctx context.Context, refreshToken string) (identifier.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(identifier.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockServiceMockRecorder) Refresh(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockService)(nil).Refresh), ctx, refreshToken)
}
