// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/service.go

// Package storagemocks is a generated GoMock package.
package storagemocks

import (
	context "context"
	reflect "reflect"

	model "github.com/TATAROmangol/mess/profile/internal/model"
	storage "github.com/TATAROmangol/mess/profile/internal/storage"
	postgres "github.com/TATAROmangol/mess/shared/postgres"
	gomock "github.com/golang/mock/gomock"
)

// MockProfile is a mock of Profile interface.
type MockProfile struct {
	ctrl     *gomock.Controller
	recorder *MockProfileMockRecorder
}

// MockProfileMockRecorder is the mock recorder for MockProfile.
type MockProfileMockRecorder struct {
	mock *MockProfile
}

// NewMockProfile creates a new mock instance.
func NewMockProfile(ctrl *gomock.Controller) *MockProfile {
	mock := &MockProfile{ctrl: ctrl}
	mock.recorder = &MockProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfile) EXPECT() *MockProfileMockRecorder {
	return m.recorder
}

// AddProfile mocks base method.
func (m *MockProfile) AddProfile(ctx context.Context, subjID, alias string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProfile", ctx, subjID, alias)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProfile indicates an expected call of AddProfile.
func (mr *MockProfileMockRecorder) AddProfile(ctx, subjID, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProfile", reflect.TypeOf((*MockProfile)(nil).AddProfile), ctx, subjID, alias)
}

// DeleteAvatarKey mocks base method.
func (m *MockProfile) DeleteAvatarKey(ctx context.Context, subjID string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatarKey", ctx, subjID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAvatarKey indicates an expected call of DeleteAvatarKey.
func (mr *MockProfileMockRecorder) DeleteAvatarKey(ctx, subjID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatarKey", reflect.TypeOf((*MockProfile)(nil).DeleteAvatarKey), ctx, subjID)
}

// DeleteProfile mocks base method.
func (m *MockProfile) DeleteProfile(ctx context.Context, subjID string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, subjID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockProfileMockRecorder) DeleteProfile(ctx, subjID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockProfile)(nil).DeleteProfile), ctx, subjID)
}

// GetProfileFromSubjectID mocks base method.
func (m *MockProfile) GetProfileFromSubjectID(ctx context.Context, subjID string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromSubjectID", ctx, subjID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromSubjectID indicates an expected call of GetProfileFromSubjectID.
func (mr *MockProfileMockRecorder) GetProfileFromSubjectID(ctx, subjID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromSubjectID", reflect.TypeOf((*MockProfile)(nil).GetProfileFromSubjectID), ctx, subjID)
}

// GetProfilesFromAlias mocks base method.
func (m *MockProfile) GetProfilesFromAlias(ctx context.Context, alias string, filter *postgres.PaginationFilter) ([]*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilesFromAlias", ctx, alias, filter)
	ret0, _ := ret[0].([]*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfilesFromAlias indicates an expected call of GetProfilesFromAlias.
func (mr *MockProfileMockRecorder) GetProfilesFromAlias(ctx, alias, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilesFromAlias", reflect.TypeOf((*MockProfile)(nil).GetProfilesFromAlias), ctx, alias, filter)
}

// UpdateAvatarKey mocks base method.
func (m *MockProfile) UpdateAvatarKey(ctx context.Context, subjID, avatarKey string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarKey", ctx, subjID, avatarKey)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatarKey indicates an expected call of UpdateAvatarKey.
func (mr *MockProfileMockRecorder) UpdateAvatarKey(ctx, subjID, avatarKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarKey", reflect.TypeOf((*MockProfile)(nil).UpdateAvatarKey), ctx, subjID, avatarKey)
}

// UpdateProfileMetadata mocks base method.
func (m *MockProfile) UpdateProfileMetadata(ctx context.Context, subjectID string, prevVersion int, alias string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileMetadata", ctx, subjectID, prevVersion, alias)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileMetadata indicates an expected call of UpdateProfileMetadata.
func (mr *MockProfileMockRecorder) UpdateProfileMetadata(ctx, subjectID, prevVersion, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileMetadata", reflect.TypeOf((*MockProfile)(nil).UpdateProfileMetadata), ctx, subjectID, prevVersion, alias)
}

// MockAvatarOutbox is a mock of AvatarOutbox interface.
type MockAvatarOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarOutboxMockRecorder
}

// MockAvatarOutboxMockRecorder is the mock recorder for MockAvatarOutbox.
type MockAvatarOutboxMockRecorder struct {
	mock *MockAvatarOutbox
}

// NewMockAvatarOutbox creates a new mock instance.
func NewMockAvatarOutbox(ctrl *gomock.Controller) *MockAvatarOutbox {
	mock := &MockAvatarOutbox{ctrl: ctrl}
	mock.recorder = &MockAvatarOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarOutbox) EXPECT() *MockAvatarOutboxMockRecorder {
	return m.recorder
}

// AddKey mocks base method.
func (m *MockAvatarOutbox) AddKey(ctx context.Context, subjectID, key string) (*model.AvatarOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKey", ctx, subjectID, key)
	ret0, _ := ret[0].(*model.AvatarOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKey indicates an expected call of AddKey.
func (mr *MockAvatarOutboxMockRecorder) AddKey(ctx, subjectID, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKey", reflect.TypeOf((*MockAvatarOutbox)(nil).AddKey), ctx, subjectID, key)
}

// DeleteKeys mocks base method.
func (m *MockAvatarOutbox) DeleteKeys(ctx context.Context, keys []string) ([]*model.AvatarOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeys", ctx, keys)
	ret0, _ := ret[0].([]*model.AvatarOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKeys indicates an expected call of DeleteKeys.
func (mr *MockAvatarOutboxMockRecorder) DeleteKeys(ctx, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeys", reflect.TypeOf((*MockAvatarOutbox)(nil).DeleteKeys), ctx, keys)
}

// GetKeys mocks base method.
func (m *MockAvatarOutbox) GetKeys(ctx context.Context, limit int) ([]*model.AvatarOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, limit)
	ret0, _ := ret[0].([]*model.AvatarOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockAvatarOutboxMockRecorder) GetKeys(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockAvatarOutbox)(nil).GetKeys), ctx, limit)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AvatarOutbox mocks base method.
func (m *MockService) AvatarOutbox() storage.AvatarOutbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarOutbox")
	ret0, _ := ret[0].(storage.AvatarOutbox)
	return ret0
}

// AvatarOutbox indicates an expected call of AvatarOutbox.
func (mr *MockServiceMockRecorder) AvatarOutbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarOutbox", reflect.TypeOf((*MockService)(nil).AvatarOutbox))
}

// Profile mocks base method.
func (m *MockService) Profile() storage.Profile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(storage.Profile)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockServiceMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockService)(nil).Profile))
}

// WithTransaction mocks base method.
func (m *MockService) WithTransaction(ctx context.Context) (storage.ServiceTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx)
	ret0, _ := ret[0].(storage.ServiceTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockServiceMockRecorder) WithTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockService)(nil).WithTransaction), ctx)
}

// MockServiceTransaction is a mock of ServiceTransaction interface.
type MockServiceTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockServiceTransactionMockRecorder
}

// MockServiceTransactionMockRecorder is the mock recorder for MockServiceTransaction.
type MockServiceTransactionMockRecorder struct {
	mock *MockServiceTransaction
}

// NewMockServiceTransaction creates a new mock instance.
func NewMockServiceTransaction(ctrl *gomock.Controller) *MockServiceTransaction {
	mock := &MockServiceTransaction{ctrl: ctrl}
	mock.recorder = &MockServiceTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceTransaction) EXPECT() *MockServiceTransactionMockRecorder {
	return m.recorder
}

// AvatarOutbox mocks base method.
func (m *MockServiceTransaction) AvatarOutbox() storage.AvatarOutbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarOutbox")
	ret0, _ := ret[0].(storage.AvatarOutbox)
	return ret0
}

// AvatarOutbox indicates an expected call of AvatarOutbox.
func (mr *MockServiceTransactionMockRecorder) AvatarOutbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarOutbox", reflect.TypeOf((*MockServiceTransaction)(nil).AvatarOutbox))
}

// Commit mocks base method.
func (m *MockServiceTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockServiceTransactionMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockServiceTransaction)(nil).Commit))
}

// Profile mocks base method.
func (m *MockServiceTransaction) Profile() storage.Profile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(storage.Profile)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockServiceTransactionMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockServiceTransaction)(nil).Profile))
}

// Rollback mocks base method.
func (m *MockServiceTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockServiceTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockServiceTransaction)(nil).Rollback))
}
