// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/service.go

// Package storagemocks is a generated GoMock package.
package storagemocks

import (
	context "context"
	reflect "reflect"

	model "github.com/TATAROmangol/mess/profile/internal/model"
	storage "github.com/TATAROmangol/mess/profile/internal/storage"
	gomock "github.com/golang/mock/gomock"
)

// MockProfile is a mock of Profile interface.
type MockProfile struct {
	ctrl     *gomock.Controller
	recorder *MockProfileMockRecorder
}

// MockProfileMockRecorder is the mock recorder for MockProfile.
type MockProfileMockRecorder struct {
	mock *MockProfile
}

// NewMockProfile creates a new mock instance.
func NewMockProfile(ctrl *gomock.Controller) *MockProfile {
	mock := &MockProfile{ctrl: ctrl}
	mock.recorder = &MockProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfile) EXPECT() *MockProfileMockRecorder {
	return m.recorder
}

// AddProfile mocks base method.
func (m *MockProfile) AddProfile(ctx context.Context, subjID, alias string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProfile", ctx, subjID, alias)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProfile indicates an expected call of AddProfile.
func (mr *MockProfileMockRecorder) AddProfile(ctx, subjID, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProfile", reflect.TypeOf((*MockProfile)(nil).AddProfile), ctx, subjID, alias)
}

// DeleteAvatarKey mocks base method.
func (m *MockProfile) DeleteAvatarKey(ctx context.Context, subjID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatarKey", ctx, subjID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatarKey indicates an expected call of DeleteAvatarKey.
func (mr *MockProfileMockRecorder) DeleteAvatarKey(ctx, subjID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatarKey", reflect.TypeOf((*MockProfile)(nil).DeleteAvatarKey), ctx, subjID)
}

// DeleteProfile mocks base method.
func (m *MockProfile) DeleteProfile(ctx context.Context, subjID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, subjID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockProfileMockRecorder) DeleteProfile(ctx, subjID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockProfile)(nil).DeleteProfile), ctx, subjID)
}

// GetProfileFromSubjectID mocks base method.
func (m *MockProfile) GetProfileFromSubjectID(ctx context.Context, subjID string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileFromSubjectID", ctx, subjID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileFromSubjectID indicates an expected call of GetProfileFromSubjectID.
func (mr *MockProfileMockRecorder) GetProfileFromSubjectID(ctx, subjID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileFromSubjectID", reflect.TypeOf((*MockProfile)(nil).GetProfileFromSubjectID), ctx, subjID)
}

// GetProfilesFromAlias mocks base method.
func (m *MockProfile) GetProfilesFromAlias(ctx context.Context, size int, asc bool, sortLabel storage.Label, alias string) (string, []*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilesFromAlias", ctx, size, asc, sortLabel, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]*model.Profile)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProfilesFromAlias indicates an expected call of GetProfilesFromAlias.
func (mr *MockProfileMockRecorder) GetProfilesFromAlias(ctx, size, asc, sortLabel, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilesFromAlias", reflect.TypeOf((*MockProfile)(nil).GetProfilesFromAlias), ctx, size, asc, sortLabel, alias)
}

// GetProfilesFromAliasWithToken mocks base method.
func (m *MockProfile) GetProfilesFromAliasWithToken(ctx context.Context, token, alias string) (string, []*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilesFromAliasWithToken", ctx, token, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]*model.Profile)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProfilesFromAliasWithToken indicates an expected call of GetProfilesFromAliasWithToken.
func (mr *MockProfileMockRecorder) GetProfilesFromAliasWithToken(ctx, token, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilesFromAliasWithToken", reflect.TypeOf((*MockProfile)(nil).GetProfilesFromAliasWithToken), ctx, token, alias)
}

// UpdateAvatarKey mocks base method.
func (m *MockProfile) UpdateAvatarKey(ctx context.Context, subjID, avatarKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarKey", ctx, subjID, avatarKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatarKey indicates an expected call of UpdateAvatarKey.
func (mr *MockProfileMockRecorder) UpdateAvatarKey(ctx, subjID, avatarKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarKey", reflect.TypeOf((*MockProfile)(nil).UpdateAvatarKey), ctx, subjID, avatarKey)
}

// UpdateProfileMetadata mocks base method.
func (m *MockProfile) UpdateProfileMetadata(ctx context.Context, subjectID string, prevVersion int, alias string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileMetadata", ctx, subjectID, prevVersion, alias)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileMetadata indicates an expected call of UpdateProfileMetadata.
func (mr *MockProfileMockRecorder) UpdateProfileMetadata(ctx, subjectID, prevVersion, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileMetadata", reflect.TypeOf((*MockProfile)(nil).UpdateProfileMetadata), ctx, subjectID, prevVersion, alias)
}

// MockAvatarKeyOutbox is a mock of AvatarKeyOutbox interface.
type MockAvatarKeyOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarKeyOutboxMockRecorder
}

// MockAvatarKeyOutboxMockRecorder is the mock recorder for MockAvatarKeyOutbox.
type MockAvatarKeyOutboxMockRecorder struct {
	mock *MockAvatarKeyOutbox
}

// NewMockAvatarKeyOutbox creates a new mock instance.
func NewMockAvatarKeyOutbox(ctrl *gomock.Controller) *MockAvatarKeyOutbox {
	mock := &MockAvatarKeyOutbox{ctrl: ctrl}
	mock.recorder = &MockAvatarKeyOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarKeyOutbox) EXPECT() *MockAvatarKeyOutboxMockRecorder {
	return m.recorder
}

// AddKey mocks base method.
func (m *MockAvatarKeyOutbox) AddKey(ctx context.Context, subjectID, key string) (*model.AvatarKeyOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKey", ctx, subjectID, key)
	ret0, _ := ret[0].(*model.AvatarKeyOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKey indicates an expected call of AddKey.
func (mr *MockAvatarKeyOutboxMockRecorder) AddKey(ctx, subjectID, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKey", reflect.TypeOf((*MockAvatarKeyOutbox)(nil).AddKey), ctx, subjectID, key)
}

// DeleteKeys mocks base method.
func (m *MockAvatarKeyOutbox) DeleteKeys(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeys", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeys indicates an expected call of DeleteKeys.
func (mr *MockAvatarKeyOutboxMockRecorder) DeleteKeys(ctx, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeys", reflect.TypeOf((*MockAvatarKeyOutbox)(nil).DeleteKeys), ctx, keys)
}

// GetKeys mocks base method.
func (m *MockAvatarKeyOutbox) GetKeys(ctx context.Context, limit int) ([]*model.AvatarKeyOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, limit)
	ret0, _ := ret[0].([]*model.AvatarKeyOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockAvatarKeyOutboxMockRecorder) GetKeys(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockAvatarKeyOutbox)(nil).GetKeys), ctx, limit)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AvatarKeyOutbox mocks base method.
func (m *MockService) AvatarKeyOutbox() storage.AvatarKeyOutbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarKeyOutbox")
	ret0, _ := ret[0].(storage.AvatarKeyOutbox)
	return ret0
}

// AvatarKeyOutbox indicates an expected call of AvatarKeyOutbox.
func (mr *MockServiceMockRecorder) AvatarKeyOutbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarKeyOutbox", reflect.TypeOf((*MockService)(nil).AvatarKeyOutbox))
}

// Profile mocks base method.
func (m *MockService) Profile() storage.Profile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(storage.Profile)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockServiceMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockService)(nil).Profile))
}

// WithTransaction mocks base method.
func (m *MockService) WithTransaction(ctx context.Context) (storage.ServiceTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx)
	ret0, _ := ret[0].(storage.ServiceTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockServiceMockRecorder) WithTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockService)(nil).WithTransaction), ctx)
}

// MockServiceTransaction is a mock of ServiceTransaction interface.
type MockServiceTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockServiceTransactionMockRecorder
}

// MockServiceTransactionMockRecorder is the mock recorder for MockServiceTransaction.
type MockServiceTransactionMockRecorder struct {
	mock *MockServiceTransaction
}

// NewMockServiceTransaction creates a new mock instance.
func NewMockServiceTransaction(ctrl *gomock.Controller) *MockServiceTransaction {
	mock := &MockServiceTransaction{ctrl: ctrl}
	mock.recorder = &MockServiceTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceTransaction) EXPECT() *MockServiceTransactionMockRecorder {
	return m.recorder
}

// AvatarKeyOutbox mocks base method.
func (m *MockServiceTransaction) AvatarKeyOutbox() storage.AvatarKeyOutbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvatarKeyOutbox")
	ret0, _ := ret[0].(storage.AvatarKeyOutbox)
	return ret0
}

// AvatarKeyOutbox indicates an expected call of AvatarKeyOutbox.
func (mr *MockServiceTransactionMockRecorder) AvatarKeyOutbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvatarKeyOutbox", reflect.TypeOf((*MockServiceTransaction)(nil).AvatarKeyOutbox))
}

// Commit mocks base method.
func (m *MockServiceTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockServiceTransactionMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockServiceTransaction)(nil).Commit))
}

// Profile mocks base method.
func (m *MockServiceTransaction) Profile() storage.Profile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(storage.Profile)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockServiceTransactionMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockServiceTransaction)(nil).Profile))
}

// Rollback mocks base method.
func (m *MockServiceTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockServiceTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockServiceTransaction)(nil).Rollback))
}
