FROM golang:1.25.5-alpine AS builder
WORKDIR /temp
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /temp/app .
CMD ["./app"]