// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/jwt/jwt.go

// Package jwtmock is a generated GoMock package.
package jwtmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GenerateAccessTokenWithUserID mocks base method.
func (m *MockService) GenerateAccessTokenWithUserID(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessTokenWithUserID", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessTokenWithUserID indicates an expected call of GenerateAccessTokenWithUserID.
func (mr *MockServiceMockRecorder) GenerateAccessTokenWithUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessTokenWithUserID", reflect.TypeOf((*MockService)(nil).GenerateAccessTokenWithUserID), userID)
}

// GenerateRefreshTokenWithUserID mocks base method.
func (m *MockService) GenerateRefreshTokenWithUserID(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshTokenWithUserID", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshTokenWithUserID indicates an expected call of GenerateRefreshTokenWithUserID.
func (mr *MockServiceMockRecorder) GenerateRefreshTokenWithUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshTokenWithUserID", reflect.TypeOf((*MockService)(nil).GenerateRefreshTokenWithUserID), userID)
}

// GetUserIDFromToken mocks base method.
func (m *MockService) GetUserIDFromToken(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromToken", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDFromToken indicates an expected call of GetUserIDFromToken.
func (mr *MockServiceMockRecorder) GetUserIDFromToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromToken", reflect.TypeOf((*MockService)(nil).GetUserIDFromToken), token)
}
